- name: Add the MongoDB GPG key to apt.
  sudo: yes
  apt_key: url=http://docs.mongodb.org/10gen-gpg-key.asc state=present
  
- name: Add the MongoDB repository.
  sudo: yes
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present

- name: Install MongoDB
  sudo: yes
  apt: name=mongodb-org state=installed