language: python

python:
  - "3.6"

sudo: required

services:
  - docker

cache: pip

env:
  global:
    - DATABASE_URL=postgresql://demo:demo@localhost:5432/demokratikollen
    - DATABASE_RIKSDAGEN_URL=postgresql://demo:demo@localhost:5432/riksdagen
    - MONGO_DATABASE_URL=mongodb://localhost:27017/local
    - PYTHONPATH=$TRAVIS_BUILD_DIR

before_install:
  - openssl aes-256-cbc -K $encrypted_dac1b8060600_key -iv $encrypted_dac1b8060600_iv -in ci/deploy_key.enc -out ci/deploy_key -d
  - "sudo service postgresql stop || :"
  - "sudo service mongod stop || :"

install: pip install -r demokratikollen/requirements/dev.txt

before_script:
  - pushd docker/compose/test
  - docker-compose up -d
  - docker ps -a
  - popd
  - sleep 60

jobs:
  include:
    - script: py.test demokratikollen
# Skip for now as it's not really working
#    - script: behave demokratikollen/www/features
    - stage: docker
      install: skip
      before_script: skip
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./ci/build_docker_image.sh; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./ci/build_data_images.sh; fi'
    - stage: deploy
      script: skip
      install: skip
      before_script: skip
      deploy:
        skip_cleanup: true
        provider: script
        script: ci/deploy.sh
        on:
          branch: develop