language: python

python:
  - "3.6"

services:
  - postgresql
  - mongodb

env:
  global:
    - DATABASE_URL="postgresql://postgres:@localhost/"
    - MONGO_DATABASE_URL="localhost"

install: pip install -r demokratikollen/requirements/dev.txt

before_script:
  - gunzip demokratikollen/data/dumps/postgres_dump.sql.gz | psql -U postgres
  - tar -xf demokratikollen/data/dumps/mongodb_dump.tar.gz
  - mongorestore mongodb_dump

script: nosetests demokratikollen/www/specs


