- name: Check if lock-file exists
  stat: path=/home/wercker/deploy.lock
  register: lock
- fail: msg="Lockfile exists. Either a deploy is running or the last deploy failed somehow. Exiting..."
  when: lock.stat.exists

- name: Copy the docker related files.
  synchronize: src=./ dest=/home/wercker/docker/

- name: Copy the source to the webapp
  synchronize: src=../demokratikollen/ dest=/home/wercker/docker/webapp/demokratikollen/ rsync_opts=--exclude=temp

- name: Copy the source to the bgtask 
  synchronize: src=../demokratikollen/ dest=/home/wercker/docker/bgtasks/demokratikollen/ rsync_opts=--exclude=temp

- name: Remove the www folder from bgtask
  shell: rm -rf docker/bgtasks/demokratikollen/www

- name: Copy the static files to the nginx docker.
  synchronize: src=../demokratikollen/www/app/static/ dest=/home/wercker/docker/nginx/static/