- name: Fire shell script for starting postgres containers.
  shell: bash docker/postgres/start_container.sh
  ignore_errors: True

#- name: Fire shell script for creating a new webapp container
#  shell: bash docker/webapp/create_image.sh
#  ignore_errors: True

#- name: Fire shell script for creating a new bgtasks image
#  shell: bash docker/bgtasks/create_image.sh
#  ignore_errors: True