- name: Install Postgresql ubuntu packages
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
      - postgresql
      - libpq-dev # Required for Ansible to interact with postgres
      - python-psycopg2 # required for ansible to interact with postgres

- name: Copy posgresql configs.
  sudo: yes
  copy: src={{item.file}} dest={{item.path}} 
  with_items:
    - {file: 'postgresql.conf', path: '/etc/postgresql/9.3/main/postgresql.conf'}
    - {file: 'pg_hba.conf', path: '/etc/postgresql/9.3/main/pg_hba.conf'}
    - {file: '.pgpass', path: '~/.pgpass'}
  notify:
      - Restart Postgres

- name: Create Databases
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ item }}
  with_items:
    - '{{ db_name }}'
    - riksdagen

- name: Create User
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ db_user }} password={{ db_password }} state=present role_attr_flags=NOSUPERUSER,CREATEDB

- name: Provide user with DB permissions
  sudo: yes
  sudo_user: postgres
  postgresql_user: user={{ db_user }} db={{ item }} priv=ALL
  with_items:
    - '{{ db_name }}'
    - riksdagen

- name: Set DATABASE_USER in env
  lineinfile: dest=~/.bashrc state=present line='export {{ item.key }}="{{ item.value }}"'
  with_items:
    - {key: 'DATABASE_USER', value: '{{ db_user }}'}
    - {key: 'DATABASE_PWD', value: '{{ db_password }}'}
    - {key: 'DATABASE_URL', value: 'postgresql://{{db_user}}:{{db_password}}@localhost:5432/{{db_name}}'}
    - {key: 'DATABASE_NAME', value: '{{ db_name }}'}
    - {key: 'DATABASE_RIKSDAGEN_URL', value: 'postgresql://{{db_user}}:{{db_password}}@localhost:5432/riksdagen'}