- name: Allow password authentication for local socket users
  sudo: yes
  lineinfile: dest=/etc/postgresql/9.3/main/pg_hba.conf state=present line='local all all md5'
  notify:
      - Restart Postgres

- name: Create Database
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ db_name }}

- name: Create User
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ db_user }} password={{ db_password }} state=present role_attr_flags=NOSUPERUSER,CREATEDB

- name: Provide user with DB permissions
  sudo: yes
  sudo_user: postgres
  postgresql_user: user={{ db_user }} db={{ db_name }} priv=ALL

- name: Set the DB url ENV for the app
  lineinfile: dest=~/.bashrc state=present line='export DATABASE_URL="postgresql://{{db_user}}:{{db_password}}@localhost:5432/{{db_name}}"'
