- name: Check if lock-file exists
  stat: path=/home/deploy/deploy.lock
  register: lock
- fail: msg="Lockfile exists. Either a deploy is running or the last deploy failed somehow. Exiting..."
  when: lock.stat.exists

# - name: Remove the old_old source
#   file: path=/home/deploy/demokratikollen_old state=absent

# - name: Move the old src
#	shell: mv /home/deploy/demokratikollen /home/deploy/demokratikollen_old

# - name: Fetch the source.
#   git: repo=https://github.com/joelgoop/demokratikollen.git dest=/home/deploy/demokratikollen version=new-deploy

- name: Set cookie secret for the webapp container.
  lineinfile: dest=/home/deploy/demokratikollen/deployment/docker/webapp/Dockerfile line='ENV SECRET_KEY {{ lookup("env","SECRET_KEY") }}' state=present

- name: Set CSRF secret for the webapp container.
  lineinfile: dest=/home/deploy/demokratikollen/deployment/docker/webapp/Dockerfile line='ENV CSRF_SESSION_KEY {{ lookup("env","CSRF_SESSION_KEY") }}' state=present