- name: Install Python related ubuntu packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      - python-setuptools
      - python-dev
      - python3.4-dev

- name: Install build-deps for matplotlib
  sudo: yes
  shell: apt-get -y build-dep python3-matplotlib python3-numpy python-numpy python-matplotlib

- name: Install virtualenv
  sudo: yes
  easy_install: name=virtualenv

- name: Create virtualenv directory 
  shell: mkdir -p {{venv_dir}}
  changed_when: False

- name: Create the 2.7 virtualenv.
  shell: virtualenv {{venv_dir}}/python2.7
  changed_when: False

- name: Create the 3.4 virtualenv.
  shell: pyvenv-3.4 --without-pip {{venv_dir}}/python3.4
  changed_when: False

- name: Do the Pip workaround
  shell: source {{venv_dir}}/python3.4/bin/activate && curl https://bootstrap.pypa.io/get-pip.py | python
  args:
    executable: /bin/bash

- name: Choose the 3.4 virtualenv on logins 
  lineinfile: dest=~/.bashrc state=present line='source {{venv_dir}}/python3.4/bin/activate'
