version: "3"

services:
  web:
    image: dev_web
    command: gunicorn -c demokratikollen/www/gunicorn_production_config.py demokratikollen.www.gunicorn_production:app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://demo:demo@postgres:5432/demokratikollen
      - DATABASE_RIKSDAGEN_URL=postgresql://demo:demo@postgres:5432/riksdagen
      - MONGO_DATABASE_URL=mongodb://mongo:27017/local
    depends_on:
      - postgres
      - mongo

  postgres:
    image: demokratikollen/postgres:${postgres_md5}

  mongo:
    image: demokratikollen/mongodb:${mongodb_md5}

