- hosts: demokratikollen
  remote_user: wercker
  sudo_user: wercker
  vars:
      app_name: demokratikollen
  roles:
      - image_creation
      #- mongodb
      #- webapp
      #- nginx
      #- post-setup