- name: Install NodeSource repo
  sudo: yes
  shell: curl -sL https://deb.nodesource.com/setup | bash -

- name: Install Node.js
  sudo: yes
  apt: name=nodejs

- name: Set ownership on /usr/local/
  sudo: yes
  shell: chown -R {{usr_local_owner}} /usr/local/

- name: Tell npm to install things under /usr/local
  command: npm config set prefix "/usr/local"

- name: Install Node.js packages
  npm: state=present global=yes name={{item}}
  with_items:
      - grunt-cli

- name: Install Bootstrap and Compass
  gem: name={{item}} state=present
  with_items:
      - bootstrap-sass
      - compass

