- name: Install NodeSource repo
  sudo: yes
  shell: curl -sL https://deb.nodesource.com/setup | bash -

- name: Install Node.js
  sudo: yes
  apt: name=nodejs

- name: Set ownership on /usr/local/
  sudo: yes
  shell: chown -R {{usr_local_owner}} /usr/local/

- name: Tell npm to install things under /usr/local
  command: npm config set prefix "/usr/local"

- name: Install Node.js packages
  npm: state=present global=yes name={{item}}
  with_items:
      - grunt-cli

- name: Install some Ruby gems
  sudo: yes
  gem: name={{item}} state=present user_install=no
  with_items:
      - bootstrap-sass
      - compass
      - bundler

- name: Install bootstrap into Compass project
  command: compass install bootstrap -c {{compass_dir}}/config.rb --app-dir {{compass_dir}}
  ignore_errors: True