- name: Install NodeSource repo
  sudo: yes
  shell: curl -sL https://deb.nodesource.com/setup | bash -

- name: Install Node.js
  sudo: yes
  apt: name=nodejs

- name: Set ownership on /usr/local/
  sudo: yes
  shell: chown -R {{usr_local_owner}} /usr/local/

- name: Tell npm to install things under /usr/local
  command: npm config set prefix "/usr/local"

- name: Install global Node.js packages
  npm: state=present global=yes name={{item}}
  with_items:
      - gulp
      - bower
      # - node-sass

- name: Install some Ruby gems
  sudo: yes
  gem: name={{item}} state=present user_install=no
  with_items:
      - sass

- name: Symlink package.json for npm dev dependencies
  file: src={{design_dir}}/package.json dest=~/package.json state=link

- name: Install Node.js packages for design stuff
  command: chdir=~/ npm install

- name: Install Bower packages for design stuff
  command: chdir={{design_dir}} bower install

- name: Run gulp to provide front-end dependencies
  command: chdir={{design_dir}} gulp all