- name: Add the nodejs repository.
  sudo: yes
  apt_repository: repo='ppa:chris-lea/node.js' state=present
  register: result

- name: Update apt if we added the repo.
  sudo: yes
  apt: update_cache=yes
  when: result|changed

- name: Install nodejs
  sudo: yes
  apt: name={{item}} state=installed
  with_items:
      - nodejs