- name: Set deployment status
  shell: echo "{{ lookup("env","DEPLOY") }}" > /home/deploy/demokratikollen/deployment/deploy.conf

- name: Start deployment script
  shell: python3 /home/deploy/demokratikollen/deployment/deployment.py