- name: Install nginx ubuntu packag
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      - nginx
      - phantomjs

- name: Copy nginx config.
  sudo: yes
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf  
  notify:
    - Restart Nginx
