- name: Upgrade ubuntu packages
  sudo: yes
  apt: upgrade=yes update_cache=yes

- name: Install ubuntu packages
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
      - unzip
      - ruby-dev
      - git-core

- name: Copy config files
  copy: src={{item.file}} dest={{item.path}}
  with_items:
      - {file: '.bashrc', path: '~/.bashrc'}

- name: Set base path for git repo
  lineinfile: dest=~/.bashrc state=present line='export REPO_PATH="/vagrant"'
