- name: Upgrade ubuntu packages
  sudo: yes
  apt: upgrade=yes

- name: Install ubuntu packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      - unzip

- name: Copy config files
  copy: src={{item.file}} dest={{item.path}}
  with_items:
      - {file: '.bashrc', path: '~/.bashrc'}

- name: Set base path for git repo
  lineinfile: dest=~/.bashrc state=present line='export REPO_PATH="/vagrant"'
