- name: Build a new postgres image if the schema changed
  docker_image: name={{ app_name }}/postgres tag=one path=/home/wercker/docker/postgres state=present
  register: postgres_one
  when: sync_result_postgres | changed

- name: Build a new postgres image if the schema changed
  docker_image: name={{ app_name }}/postgres tag=two path=/home/wercker/docker/postgres state=present
  register: postgres_two
  when: sync_result_postgres | changed

- name: Start postgres image.
  docker: image={{ app_name }}/postgres:one name=postgres_one
  when: postgres_one | changed

- name: Start postgres image.
  docker: image={{ app_name }}/postgres:two name=postgres_two
  when: postgres_two | changed

- name: Record which instance is the newest
  shell: echo "one" > /home/wercker/postgres.which
  when: postgres_one | changed

- name: Record which instance is the newest
  shell: echo "two" > /home/wercker/postgres.which
  when: postgres_two | changed